### PR TITLE
Feature/label support

### PR DESCRIPTION
**Pull request by WoLpH**
Added support for Label objects

### CODE REVIEW

**Comment by WoLpH** [comment]
This pull-request is based on the changes made in #24, merging this will effectively merge both.

**Comment by plish** [comment]
Really on it aren't you :)

**Comment by WoLpH** [comment]
Haha, yeah... Needed some trello support for a little project of mine. Based the first version on py-trello but that one really sucks, this project is much better :)

**Comment by plish** [comment]
Thanks mate, that's the reason I wrote this one to begin with :)

**Pull request merged**
